# One or more robots to add to the scene
robots:
  - serial_number: "Rizon4-00001" # Serial number of robot 1
    usd: "/path/to/robot1.usd"    # Path to the usd file of robot 1
    position:                     # Position in world frame to put robot 1
      x: 0.0
      y: 0.0
      z: 0.0
    orientation:                  # Orientation (quaternion) in world frame to put robot 1
      w: 1.0
      x: 0.0
      y: 0.0
      z: 0.0

  - serial_number: "Rizon4-00002" # Serial number of robot 2
    usd: "/path/to/robot2.usd"    # Path to the usd file of robot 2
    position:                     # Position in world frame to put robot 2
      x: 1.0
      y: 0.0
      z: 0.0
    orientation:                  # Orientation (quaternion) in world frame to put robot 2
      w: 1.0
      x: 0.0
      y: 0.0
      z: 0.0
  
  # More robots ...

# Path to the usd of the environment to load. 
# If not provided, an empty environment with default ground plane will be used.
env_usd: "/path/to/environment.usd"

# Enable GPU dynamics. Use this argument if any object in the scene requires GPU for dynamics computation. 
# For example, deformable body material and SDF mesh collider.
gpu_dynamics: false

# One or more cameras to add to the scene
cameras:
  - name: "camera_1"        # Unique name of camera 1
    resolution: [1280, 720] # Resolution of camera 1
    fps: 30                 # Frames per second of camera 1
    focal_length: 2.5       # Focal length in meter of camera 1
    position:               # Position in world frame to put camera 1
      x: 0.0
      y: 0.0
      z: 0.0
    orientation:            # Orientation (quaternion) in USD frame to put camera 1
      w: 1.0
      x: 0.0
      y: 0.0
      z: 0.0

  - name: "camera_2"        # Unique name of camera 2
    resolution: [1280, 720] # Resolution of camera 2
    fps: 30                 # Frames per second of camera 2
    focal_length: 2.5       # Focal length in meter of camera 2
    position:               # Position in world frame to put camera 2
      x: 0.0
      y: 0.0
      z: 0.0
    orientation:            # Orientation (quaternion) in USD frame to put camera 2
      w: 1.0
      x: 0.0
      y: 0.0
      z: 0.0

  # More cameras ...
